version: '3'
services:
  master:
    build:
      context: .  # Utilise le répertoire actuel comme contexte de construction
      dockerfile: ./master.Dockerfile  # Chemin vers le Dockerfile spécifique
    working_dir: /root/playbooks  # Le répertoire de travail dans le conteneur
    volumes:
      - /home/vagrant/playbooks:/home/ansadmin/playbooks  # Montage du volume
    command: tail -f /dev/null  # Maintient le conteneur actif
    #user: ansible  # Exécution en tant qu'utilisateur 'ansible'

  web:
    build:
      context: .  # Contexte de construction
      dockerfile: ./server.Dockerfile  # Dockerfile pour ce service
    volumes:
      - /home/vagrant/playbooks:/home/ansadmin/playbooks  # Montage du volume
    #command: tail -f /dev/null
    #user: ansible  # Exécution en tant qu'utilisateur 'ansible'

  db:
    build:
      context: .  # Contexte de construction
      dockerfile: ./server.Dockerfile  # Dockerfile pour ce service
    volumes:
      - /home/vagrant/playbooks:/home/ansadmin/playbooks  # Montage du volume
    #command: tail -f /dev/null
    #user: ansible  # Exécution en tant qu'utilisateur 'ansible'

  lb:
    build:
      context: .  # Contexte de construction
      dockerfile: ./server.Dockerfile  # Dockerfile pour ce service
    volumes:
      - /home/vagrant/playbooks:/home/ansadmin/playbooks  # Montage du volume
    ports: 
      - 8080:80  # Redirection du port 8080 de l'hôte vers le port 80 du conteneur
    #command: tail -f /dev/null
    #user: ansible  # Exécution en tant qu'utilisateur 'ansible'
